### ISSUE TITLE
is this a place holder ?

### ISSUE THREAD

**Issue by Nandpatel87** [xll755/ResumeMASTER#13]
https://github.com/xll755/ResumeMASTER/blob/0f163abe359ef6539dd54b35924fa674c342e3f1/www/Resume.php#L5

**Comment by tPeltier** [comment]
No, that for the PDF libs that composer installed. Now, idk if it needs to be / could be elsewhere, but it works here so 🤷

**Comment by tPeltier** [comment]
( I just reopened it cause idk if u can comment on closed issues 😂 )
